version: "3"

services:
  dog-server:
    image: nginx
    container_name: doc-server
    volumes:
      - ./dog-server/index.html:/usr/share/nginx/html/index.html
    ports:
      - 7000:80

  cat-server:
    image: nginx
    container_name: cat-server
    volumes:
      - ./cat-server/index.html:/usr/share/nginx/html/index.html
    ports:
      - 7001:80

  reverse-proxy:
    image: nginx
    volumes:
      - ./reverse-proxy/default.conf:/etc/nginx/conf.d/default.conf
      - ./reverse-proxy/index.html:/usr/share/nginx/html/index.html
    ports:
      - 80:80
