version: "3"

services:
  dog-server:
    image: nginx
    container_name: doc-server
    volumes:
      - ./dog-server:/etc/nginx/html
    ports:
      - 7000:80

  cat-server:
    image: nginx
    container_name: cat-server
    volumes:
      - ./cat-server:/etc/nginx/html
    ports:
      - 7001:80

  reverse-proxy:
    image: nginx
    volumes:
      - ./reverse-proxy/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 80:80
